server:
  port: 33400

general:
  kafka-topic: transactions

kafka:
  topic:
    transaction: transactions

spring:
  kafka:
    group-id: midas-core-group
    bootstrap-servers: localhost:9092
    #properties:
      #security.protocol: SSL
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.springframework.kafka.support.serializer.JsonDeserializer
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer:  org.springframework.kafka.support.serializer.JsonDeserializer
    general:
      kafka-topic: transactions
  datasource:
    url: jdbc:h2:file:./db/midasdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

  h2:
    console:
      enabled: true
      path: /db-console
      settings:
        web-allow-others: false